---
title: "Soil-Mates"
output: html_document
---

#### Packages
```{r}
library(dplyr)
library(vegan)
library(tidyverse)
```
#### Importing all at one
```{r}
temp <- list.files("./Data",pattern="*.csv", full.names = T) #creates an object that contains a string of file names with directory so they can be located
Dat <- list() # creates an empty vector used in the for loop
for (i in seq_along(temp)) { # creates a list (I dont know if this is the right term) of dataframes
  Dat[[i]] <- read.csv(
    file = temp[[i]]
  )
}
names <- c("En10", "En20", "Ar10", "Ba10", "Fu10", "Ar20", "Ba20", "Fu20", "En") #probably a better way to name the elements in Dat - increase reproducibility
Dat <- set_names(Dat, names) # sets the names for the data frames in Dat
```
#### Preprocessing before data is combined
```{r}
Dat$Fu10 <- Dat$Fu10 %>% #Removes extras from Fungi
  select(-Trophic.Mode,-Guild,-Confidence.Ranking)
```
```{r}
Dat$Fu20 <- Dat$Fu20 %>% #Removes extras from Fungi
  select(-Trophic.Mode,-Guild,-Confidence.Ranking) 
```
```{r}
Dat$Ba10 <- Dat$Ba10 %>% # Fixes capitalization
  rename(Cluster=(cluster)) 
```
```{r}
Dat$Ar10 <- Dat$Ar10 %>% # Fixes capitalization
  rename(Phyla=(phylum),
         Class=(class),
         Order=(order),
         Family=(family))
```
```{r}
Dat$En10 <- Dat$En10 %>% # Possibly unnecessary
  rename(Archaea=(Archaea_010cm),
         Bacteria=(Bacteria_010cm),
         Fungi=(Fungi_010cm))
```

```{r}
Dat$En20 <- Dat$En20 %>% # Makes so that when both Enviro tables are combined names match
  rename(Clearcut=(CLF),
         Salvage=(Salv_log),
         Organic.Carbon=(Organic.Carbon_prop),
         Exc.Magnesium=(Exc..Magnesium),
         pH.CaCl2.=(pH.Level..CaCl2.),
         Archaea=(Archaea_020cm),
         Bacteria=(Bacteria_020cm),
         Fungi=(Fungi_020cm)) %>%
  mutate(TSD= as.numeric(TSD)-1)
```
#### Combines datasets - reproducibility likely can be enhanced - this one uses the Importing all at once
```{r}
En<-bind_rows(Dat$En10,Dat$En20) #Combines Enviro tables into one dataset
D10<-bind_rows(Dat$Ar10,Dat$Ba10,Dat$Fu10) # Combines all for at depth 10 
D20<-bind_rows(Dat$Ar20,Dat$Ba20,Dat$Fu20) # Combines all microbes for for depth of 20
```

```{r}
#Writing En into Data folder to open in Question 2 rmd
write.csv(En, file = "./Data/En.csv")
```

#### Please ignore - this belongs in question 1
#### Diversity
```{r}
tD10 <- D10 #creates new object to be manipulated for diversity calculations
tD10 <- tD10 %>%
  select(-Cluster, -Sample, -Phyla, -Class, -Order, -Family)
tD10 <- t(tD10) #Transposes file
```

```{r}
Div1 <- diversity(tD10, index = "shannon", MARGIN = 1, base= exp(1))
```

```{r}
tD20 <- D20
tD20 <- tD20 %>%
  select(-Cluster, -Sample, -Phyla, -Class, -Order, -Family)
tD20 <- t(tD20)
```

```{r}
Div2 <- diversity(tD20, index = "shannon", MARGIN = 1, base= exp(1))
```

```{r}
EnQ1 <- En
EnQ1$Div <- c(Div1, Div2)
```

#### Add proper names to a new column for disturbance History in a New environemental table using a for loop
```{r}
EnM <- EnQ1
for (i in 1:nrow(EnM)) { 
  if (EnM$TSD[i] == 167) {
  EnM$Disturbance_History[i] <- "1850F"
  } else if (EnM$TSD[i] == 78) {
  EnM$Disturbance_History[i] <- "1939F" 
  } else if ((EnM$No.Fires[i]== 2) && (EnM$TSD[i] == 34)) {
  EnM$Disturbance_History[i] <- "1939/1983F"
  } else if ((EnM$No.Fires[i]== 2) && (EnM$Salvage[i] == 0) && (EnM$Clearcut[i] == 0) && (EnM$TSD[i] == 8)) {
  EnM$Disturbance_History[i] <- "1939/2009F" 
  } else if (EnM$No.Fires[i]== 3) {
  EnM$Disturbance_History[i] <- "1939/1983/2009F" 
  } else if ((EnM$No.Fires[i]== 1) && (EnM$Clearcut[i] == 1) && (EnM$TSD[i] == 34)) {
  EnM$Disturbance_History[i] <- "1939F/1980CC"
  } else if ((EnM$No.Fires[i]== 1) && (EnM$Clearcut[i] == 1) && (EnM$TSD[i] == 8)) {
  EnM$Disturbance_History[i] <- "1939F/2009CC"
  } else if (EnM$Salvage[i] == 1) {
  EnM$Disturbance_History[i] <- "1939/2009F/2009SL"
  } else if ((EnM$No.Fires[i]== 2) && (EnM$Clearcut[i] == 1) && (EnM$TSD[i] == 8)) {
  EnM$Disturbance_History[i] <- "1939/1983F/2009CC"
  } 
}
unique(EnM$Disturbance_History) #checks unqiue to ensure I got all the every history
```

```{r}
ggplot(EnM, aes(x=Depth, y=Div)) +
    geom_boxplot(aes(colour=I("black"), fill=Disturbance_History)) +  
    labs(y="Alpha Diversity", 
         x="Depth of sample",
         fill="Disturbance History") + 
  scale_x_discrete(labels=c("0-10cm", "20-30cm")) +
        theme_classic()
```




