---
title: "432 analysis-Logan"
author: "Logan Wisteard"
date: '2022-03-23'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Question 2. Are different soil chemical compositions associating with destructive forces?

##Introduction

## The analysis

Load packages
```{r}
library(dplyr)
library(ggplot2)
library(ggtree)
library(vegan)
library(ape)
```




```{r}
#in Soil-mates write.csv 
#can see En.csv in Data folder
#general not working why?
#en <- read.csv("/./Data/En.csv")
en <- read.csv("/Users/laurynjoslin/Dropbox/Soil-Mates/Data/En.csv")
```

```{r}
summary(en)
```

```{r}
#Destructive forces summary

#No.Fires - number of fires either 1, 2, 3 or 4
#Clearcut- is it clearcut yes = 1, no = 0
#Salvage - was it salvage logged - yes = 1, no = 0
#TSD is time since disturbance

```

```{r}
#chemical info

#colwell is a way of measuring availibility of that element
#DTPA is Diethylenetriaminepentaacetic acid which extracts trace elements
#
```


```{r}
en$no_fires <- as.character(en$No.Fires)
```


```{r}
en$clearcut <- as.character(en$Clearcut)
```

#Exploratory boxplots

```{r}
ggplot(en)+
  geom_boxplot(aes(x = no_fires, y = log10(Ammonium.Nitrogen), fill = clearcut))
```
```{r}
#No difference
ggplot(en)+
  geom_boxplot(aes(x = no_fires, y = Organic.Carbon, fill = clearcut))
```

```{r}
#No fires has higher nitrogen in nitrate form compared to all number of fires greater than 2
ggplot(en)+
  geom_boxplot(aes(x = no_fires, y = Nitrate.Nitrogen, fill = clearcut))
```

```{r}
ggplot(en)+
  geom_boxplot(aes(x = no_fires, y = log10(Phosphorus.Colwell), fill = clearcut))
```

```{r}
#three fires more potassium 
ggplot(en)+
  geom_boxplot(aes(x = no_fires, y = Potassium.Colwell,fill = clearcut))
```

```{r}
ggplot(en)+
  geom_boxplot(aes(x = no_fires, y = log10(DTPA.Copper), fill = clearcut))
```

```{r}
#lower iron 3 fires? 
ggplot(en)+
  geom_boxplot(aes(x = no_fires, y = log10(DTPA.Iron), fill = clearcut))
```

```{r}
ggplot(en)+
  geom_boxplot(aes(x = no_fires, y = log10(DTPA.Manganese), fill = clearcut))
```
```{r}
#higher magnesium with increasing number of fires 
ggplot(en)+
  geom_boxplot(aes(x = no_fires, y = log10(Exc.Magnesium), fill = clearcut))
```

#cleaner graphs

```{r}
clearcutpal <- c("#7f4f24", "#718355")
```

```{r}
theme_boxplot_one <- function (base_size =12, base_family = ""){
  theme_classic(base_size = base_size, base_family = base_family) %+replace%
    theme(
      axis.text = element_text(colour = "black"),
      axis.title.x = element_text(size=12),
      axis.text.x = element_text(size=9),
      axis.title.y = element_text(size=12, angle=90),
      axis.text.y = element_text(size=9),
      axis.ticks = element_blank(),
      panel.background = element_rect(fill = "white"),
      panel.border = element_blank(),
      plot.title= element_text(face="bold", size=24)
    )
}
```

```{r}
a <- ggplot(en)+
  geom_boxplot(aes(x = no_fires, y = Nitrate.Nitrogen, fill = clearcut))+
  scale_fill_manual(labels = c('No','Yes'), values = clearcutpal)+
  theme_boxplot_one()+
  scale_x_discrete(name = "\nNumber of forest fires")+
  scale_y_continuous(name = "Nitrate form of Nitrogen (ppm)\n")+
  labs(fill = "Was the site 
clear cut?")
a
```
```{r}
b <- ggplot(en)+
  geom_boxplot(aes(x = no_fires, y = Potassium.Colwell, fill = clearcut))+
  scale_fill_manual(labels = c('No','Yes'), values = clearcutpal)+
  theme_boxplot_one()+
  scale_x_discrete(name = "\nNumber of forest fires")+
  scale_y_continuous(name = "Potassium (ppm)\n")+
  labs(fill = "Was the site 
clear cut?")
b
```


```{r}
c <- ggplot(en)+
  geom_boxplot(aes(x = no_fires, y = log10(DTPA.Iron), fill = clearcut))+
  scale_fill_manual(labels = c('No','Yes'), values = clearcutpal)+
  theme_boxplot_one()+
  scale_x_discrete(name = "\nNumber of forest fires")+
  scale_y_continuous(name = expression(paste(log[10]," (Iron ppm)")))+
  labs(fill = "Was the site 
clear cut?")
c
```

```{r}
d <- ggplot(en)+
  geom_boxplot(aes(x = no_fires, y = Organic.Carbon, fill = clearcut))+
  scale_fill_manual(labels = c('No','Yes'), values = clearcutpal)+
  theme_boxplot_one()+
  scale_x_discrete(name = "\nNumber of forest fires")+
  scale_y_continuous(name = "Organic Carbon (ppm)\n")+
  labs(fill = "Was the site 
clear cut?")
d
```
#SALVAGE LOGGING

```{r}
en$Salvage <- as.character(en$Salvage)
```

```{r}
salvagepal <- c("#e9972d", "#15616d")
```

```{r}
e <- ggplot(en)+
  geom_boxplot(aes(x = no_fires, y = Organic.Carbon, fill = Salvage))+
  scale_fill_manual(labels = c('No','Yes'), values = salvagepal)+
  theme_boxplot_one()+
  scale_x_discrete(name = "\nNumber of forest fires")+
  scale_y_continuous(name = "Organic Carbon (ppm)\n")+
  labs(fill = "Was the site 
salvage logged??")
e
```
```{r}
f <- ggplot(en)+
  geom_boxplot(aes(x = no_fires, y = log10(DTPA.Iron), fill = Salvage))+
  scale_fill_manual(labels = c('No','Yes'), values = salvagepal)+
  theme_boxplot_one()+
  scale_x_discrete(name = "\nNumber of forest fires")+
  scale_y_continuous(name = expression(paste(log[10]," (Iron ppm)")))+
  labs(fill = "Was the site 
salvage logged?")
f
```
```{r}
g <- ggplot(en)+
  geom_boxplot(aes(x = no_fires, y = Potassium.Colwell, fill = Salvage))+
  scale_fill_manual(labels = c('No','Yes'), values = salvagepal)+
  theme_boxplot_one()+
  scale_x_discrete(name = "\nNumber of forest fires")+
  scale_y_continuous(name = "Potassium (ppm)\n")+
  labs(fill = "Was the site 
salvage logged?")
g
```

```{r}
h <- ggplot(en)+
  geom_boxplot(aes(x = no_fires, y = Nitrate.Nitrogen, fill = Salvage))+
  scale_fill_manual(labels = c('No','Yes'), values = salvagepal)+
  theme_boxplot_one()+
  scale_x_discrete(name = "\nNumber of forest fires")+
  scale_y_continuous(name = "Nitrate form of Nitrogen (ppm)\n")+
  labs(fill = "Was the site 
salvage logged?")
h
```
```{r}
library(gridExtra)
```

```{r}
grid.arrange(a, b, c, d,
             ncol = 1, nrow = 4)
```



#if we are stacking we can lose things

```{r}
a <- ggplot(en)+
  geom_boxplot(aes(x = no_fires, y = Nitrate.Nitrogen, fill = clearcut))+
  scale_fill_manual(labels = c('No','Yes'), values = clearcutpal)+
  theme_boxplot_one()+
  theme(axis.title.x = element_blank(), axis.text.x = element_blank())+
  theme(legend.position = "none")+
  scale_x_discrete(name = "\nNumber of forest fires")+
  scale_y_continuous(name = "Nitrate form of Nitrogen (ppm)\n")+
  labs(fill = "Was the site 
clear cut?")

b <- ggplot(en)+
  geom_boxplot(aes(x = no_fires, y = Potassium.Colwell, fill = clearcut))+
  scale_fill_manual(labels = c('No','Yes'), values = clearcutpal)+
  theme_boxplot_one()+
  theme(axis.title.x = element_blank(), axis.text.x = element_blank())+
  theme(legend.position = "none")+
  scale_x_discrete(name = "\nNumber of forest fires")+
  scale_y_continuous(name = "Potassium (ppm)\n")+
  labs(fill = "Was the site 
clear cut?")


c <- ggplot(en)+
  geom_boxplot(aes(x = no_fires, y = log10(DTPA.Iron), fill = clearcut))+
  scale_fill_manual(labels = c('No','Yes'), values = clearcutpal)+
  theme_boxplot_one()+
  theme(axis.title.x = element_blank(), axis.text.x = element_blank())+
  theme(legend.position = "none")+
  scale_x_discrete(name = "\nNumber of forest fires")+
  scale_y_continuous(name = expression(paste(log[10]," (Iron ppm)")))+
  labs(fill = "Was the site 
clear cut?")

d <- ggplot(en)+
  geom_boxplot(aes(x = no_fires, y = Organic.Carbon, fill = clearcut))+
  scale_fill_manual(labels = c('No','Yes'), values = clearcutpal)+
  theme_boxplot_one()+
  theme(legend.position = "none")+
  scale_x_discrete(name = "\nNumber of forest fires")+
  scale_y_continuous(name = "Organic Carbon (ppm)\n")+
  labs(fill = "Was the site 
clear cut?")


h <- ggplot(en)+
  geom_boxplot(aes(x = no_fires, y = Nitrate.Nitrogen, fill = Salvage))+
  scale_fill_manual(labels = c('No','Yes'), values = salvagepal)+
  theme_boxplot_one()+
  theme(axis.title.x = element_blank(), axis.text.x = element_blank())+
  theme(legend.position = "none")+
  scale_x_discrete(name = "\nNumber of forest fires")+
  scale_y_continuous(name = "Nitrate form of Nitrogen (ppm)\n")+
  labs(fill = "Was the site 
salvage logged?")

g <- ggplot(en)+
  geom_boxplot(aes(x = no_fires, y = Potassium.Colwell, fill = Salvage))+
  scale_fill_manual(labels = c('No','Yes'), values = salvagepal)+
  theme_boxplot_one()+
  theme(axis.title.x = element_blank(), axis.text.x = element_blank())+
  theme(legend.position = "none")+
  scale_x_discrete(name = "\nNumber of forest fires")+
  scale_y_continuous(name = "Potassium (ppm)\n")+
  labs(fill = "Was the site 
salvage logged?")

f <- ggplot(en)+
  geom_boxplot(aes(x = no_fires, y = log10(DTPA.Iron), fill = Salvage))+
  scale_fill_manual(labels = c('No','Yes'), values = salvagepal)+
  theme_boxplot_one()+
   theme(axis.title.x = element_blank(), axis.text.x = element_blank())+
  theme(legend.position = "none")+
  scale_x_discrete(name = "\nNumber of forest fires")+
  scale_y_continuous(name = expression(paste(log[10]," (Iron ppm)")))+
  labs(fill = "Was the site 
salvage logged?")

e <- ggplot(en)+
  geom_boxplot(aes(x = no_fires, y = Organic.Carbon, fill = Salvage))+
  scale_fill_manual(labels = c('No','Yes'), values = salvagepal)+
  theme_boxplot_one()+
  theme(legend.position = "none")+
  scale_x_discrete(name = "\nNumber of forest fires")+
  scale_y_continuous(name = "Organic Carbon (ppm)\n")+
  labs(fill = "Was the site 
salvage logged??")

```




